### ISSUE TITLE
How to properly execute flows with cpu/gpu requirements

### ISSUE THREAD

**Issue by christianvogellive** [PrefectHQ/prefect-ray#44]
We were wondering how to specify that a prefect flow (or even tasks) should only run on instances which fit to the resource requirements. What is the annotation to manage this on a flow/task level?
Basically we would like to use the @ray.remote(num_gpus=1) annotation of ray.

Scenario: We have a Ray-Cluster up and running which has cpu and gpu worker nodes. We now f.ex. would like to execute a flow only on the gpu nodes and have them then scale out accordingly.

We tested a bit around with num_gpus, request_cpus etc. but did not have success yet.

Here some example code:

```
from prefect import task, flow
from prefect_ray.task_runners import RayTaskRunner
import time


RayRunner = RayTaskRunner(
    address="auto",
    init_kwargs={
        "num_gpus": 2,
    }
)


@flow(name="time-wait-flow", task_runner=RayTaskRunner)
def time_wait_flow_gpu():
    factor = 50
    times = [5.0, 16.3, 25.5]
    for i in range(0, factor):
        for time_in_secs in times:
            wait_time.submit(time_in_secs)


@task
def wait_time(time_in_secs):
    time.sleep(time_in_secs)


if __name__ == "__main__":
    time_wait_flow_gpu()
```

**Comment by ahuang11** [comment]
Perhaps this link can help: 
https://docs.ray.io/en/latest/ray-core/tasks/using-ray-with-gpus.html

Something like:
```
@task
@ray.remote(num_gpus=1)   # or maybe reverse the decorators
def use_gpu():
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))
```

Let me know if that works!

**Comment by christianvogellive** [comment]
Thanks a lot for your response.
We tried mixing the ray and prefect decorators like you also suggested, but we did not have any success yet.
Therefore we are a bit uncertain how to realize the resource requirements.

Depending on the order of the two decorators the following errors are received:
```
Traceback (most recent call last):
  File "/home/christian/Documents/temp/prefect-example/ray-anyscale-stress-test/time-wait-flow.py", line 18, in <module>
    def wait_time(time_in_secs):
  File "/home/christian/Documents/temp/prefect-example/venv/lib/python3.9/site-packages/prefect/tasks.py", line 778, in task
    Task(
  File "/home/christian/Documents/temp/prefect-example/venv/lib/python3.9/site-packages/prefect/context.py", line 163, in __register_init__
    __init__(__self__, *args, **kwargs)
  File "/home/christian/Documents/temp/prefect-example/venv/lib/python3.9/site-packages/prefect/tasks.py", line 136, in __init__
    self.name = name or self.fn.__name__
AttributeError: 'RemoteFunction' object has no attribute '__name__'
```
`Traceback (most recent call last):
  File "/home/christian/Documents/temp/prefect-example/ray-anyscale-stress-test/time-wait-flow.py", line 18, in <module>
    def wait_time(time_in_secs):
  File "/home/christian/Documents/temp/prefect-example/venv/lib/python3.9/site-packages/ray/_private/worker.py", line 2603, in _make_remote
    raise TypeError(
TypeError: The @ray.remote decorator must be applied to either a function or a class.
`

**Comment by ahuang11** [comment]
Can you pass in a name to the task to test? `@task(name="task_name)"`

**Comment by ahuang11** [comment]
Okay that didn't seem to work either:
```
import ray
from prefect import task

@task(name="abc")
@ray.remote(num_gpus=1)   # or maybe reverse the decorators
def use_gpu():
    print("ray.get_gpu_ids(): {}".format(ray.get_gpu_ids()))
    print("CUDA_VISIBLE_DEVICES: {}".format(os.environ["CUDA_VISIBLE_DEVICES"]))

```

```
AttributeError: 'RemoteFunction' object has no attribute '__qualname__'
```

**Comment by madkinsz** [comment]
With Dask, we expect users to use Dask's config context manager. We could do something similar here...

```
@flow

**Comment by madkinsz** [comment]
Regarding

> AttributeError: 'RemoteFunction' object has no attribute '__qualname__'

The task decorator could be updated to not require that. I'm not sure it'll get us far this this case though.
